# Generated by Django 4.1.3 on 2022-11-30 20:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_time_name', models.CharField(max_length=15, verbose_name='Work type')),
                ('start_day', models.CharField(max_length=15, verbose_name='Start Day')),
                ('end_day', models.CharField(max_length=15, verbose_name='End Day')),
                ('start_shift', models.IntegerField(verbose_name='Start Shift')),
                ('end_shift', models.IntegerField(verbose_name='End Shift')),
                ('company_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('contact', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Contact')),
                ('city', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='City')),
                ('address', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Address')),
            ],
        ),
    ]
