# Generated by Django 4.1.3 on 2022-11-30 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyinfo',
            options={'verbose_name_plural': 'Company Info'},
        ),
    ]
