# Generated by Django 4.1.3 on 2022-12-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_info', '0002_alter_companyinfo_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=30, verbose_name='Supplier')),
                ('supplier_number', models.IntegerField(verbose_name='Supplier Number')),
                ('supplier_address', models.TextField(verbose_name='Address')),
            ],
        ),
    ]
