# Generated by Django 4.1.3 on 2022-11-30 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=35, null=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Project Name')),
                ('project_type', models.CharField(blank=True, choices=[('Course', 'Course'), ('Private Order', 'Private Order')], max_length=35, null=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Project Type')),
                ('active', models.BooleanField(verbose_name='Available')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(3)], verbose_name='Price')),
            ],
        ),
    ]
