# Generated by Django 4.1.3 on 2022-12-06 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_info', '0003_supplier'),
        ('products', '0002_alter_productclass_options_alter_products_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company_info.supplier'),
        ),
    ]
